### ISSUE TITLE
Thick-Slabbing first breaks most functions

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#103]
After SlicerQREADS loads, if changing the slice thickness is the first thing done, most other functions fail. If another function is performed before slice thickness, everything works.

**Comment by jcfr** [comment]
Following error is reported:

```pytb
Traceback (most recent call last):
  File "/home/jcfr/Projects/SlicerQReads-Release/Slicer-build/lib/SlicerQReads-4.13/qt-scripted-modules/QReads.py", line 389, in updateGUIFromParameterNode
    QReadsLogic.slabThicknessInMmToNumberOfSlices(volumeNode, slabThicknessInMm))
  File "/home/jcfr/Projects/SlicerQReads-Release/Slicer-build/lib/SlicerQReads-4.13/qt-scripted-modules/QReads.py", line 612, in slabThicknessInMmToNumberOfSlices
    assert tichknessInMm > 0
AssertionError

```

**Comment by spycolyf** [comment]
Hi @jcfr ,

This is the only hold up to start my Beta testing on Monday. Any ideas? :-|

That thicknessInMn variable is 0. What is it that causes everything to work when another button like W/L is pushed first? Thanks!

**Comment by spycolyf** [comment]
Do you thing it could be caused by the images that are loaded?

I get this error after loading the images...

Python 3.6.7 (default, Apr 22 2021, 23:20:22) [MSC v.1924 64 bit (AMD64)] on win32
>>> dicomDataDir = "C:/SlicerQReads-0.1.0-2021-04-08-win-amd64/TestImageVolumes/TestCompressed"  # input folder with DICOM files
>>> loadedNodeIDs = []  # this list will contain the list of all loaded node IDs
>>>   
>>> from DICOMLib import DICOMUtils
>>> with DICOMUtils.TemporaryDICOMDatabase() as db:
...   DICOMUtils.importDicom(dicomDataDir, db)
...   patientUIDs = db.patients()
...   for patientUID in patientUIDs:
...     loadedNodeIDs.extend(DICOMUtils.loadPatientByUID(patientUID))
... 
Switching to temporary DICOM database: C:/Users/dvp01/AppData/Local/Temp/Slicer/20210503_192342_TempDICOMDatabase
True
Loading with imageIOName: GDCM
>>> 
Traceback (most recent call last):
  File "C:/SlicerQReads-0.1.0-2021-04-27-win-amd64/lib/SlicerQReads-4.13/qt-scripted-modules/QReads.py", line 248, in _update
    values = {QReadsLogic.DICOM_TAGS[tag]: value for tag, value in QReadsLogic.dicomTagValues(node).items()}
  File "C:/SlicerQReads-0.1.0-2021-04-27-win-amd64/lib/SlicerQReads-4.13/qt-scripted-modules/QReads.py", line 753, in dicomTagValues
    return QReadsLogic.DICOM_TAG_VALUES[instanceUIDs[0]]
KeyError: '1.3.12.2.1107.5.1.4.75850.30000020080813094591000072336'
